version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
permissions:
  - object: /home/ec2-user
    pattern: "**"
    owner: ec2-user
    mode: 777
    type:
      - file
      - directory
hooks:
  BeforeInstall:
    - location: deploy/before.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/start.sh
      timeout: 300
      runas: root